services:
  documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs
     hostname:mkdocs
    command: serve --dev-add = 0.0.0.0:8100 --watch-theme
    restart: unless-stopped
    ports:
    - "8010:8010"
    volumes:
    - ./documentation:/docs:ro