"""permisions

Revision ID: 9ca21223043d
Revises: fc4e2ab14a02
Create Date: 2026-04-03 13:21:48.002035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ca21223043d'
down_revision: Union[str, Sequence[str], None] = 'fc4e2ab14a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', postgresql.ARRAY(sa.String()),server_default=sa.text("'{CAN_SELF_DELETE}'::text[]"),nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###
