"""use token since

Revision ID: eff81d44fe88
Revises: 9ca21223043d
Create Date: 2026-04-07 08:41:10.549353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff81d44fe88'
down_revision: Union[str, Sequence[str], None] = '9ca21223043d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('use_token_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'use_token_since')
    # ### end Alembic commands ###
